const header=document.querySelector('#header'),menuButton=document.querySelector('.menu-button'),mobileMenu=document.querySelector('.mobile-menu');
addEventListener('scroll',()=>header.classList.toggle('scrolled',scrollY>40),{passive:true});
menuButton.addEventListener('click',()=>{const open=mobileMenu.classList.toggle('open');menuButton.setAttribute('aria-expanded',open);menuButton.setAttribute('aria-label',open?'Close menu':'Open menu');mobileMenu.setAttribute('aria-hidden',!open);document.body.style.overflow=open?'hidden':''});
mobileMenu.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{mobileMenu.classList.remove('open');menuButton.setAttribute('aria-expanded','false');mobileMenu.setAttribute('aria-hidden','true');document.body.style.overflow=''}));
const slides=[...document.querySelectorAll('.hero-slide')],slideNumber=document.querySelector('#slide-number');let activeSlide=0,slideTimer;
function showSlide(n){slides[activeSlide].classList.remove('active');activeSlide=(n+slides.length)%slides.length;slides[activeSlide].classList.add('active');slideNumber.textContent=String(activeSlide+1).padStart(2,'0');clearInterval(slideTimer);slideTimer=setInterval(()=>showSlide(activeSlide+1),6500)}
document.querySelectorAll('.hero-controls button').forEach(b=>b.addEventListener('click',()=>showSlide(activeSlide+Number(b.dataset.dir))));
slideTimer=setInterval(()=>showSlide(activeSlide+1),6500);
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches,observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.12});
document.querySelectorAll('.reveal').forEach((el,i)=>{if(reduced)el.classList.add('visible');else{el.style.transitionDelay=`${Math.min((i%4)*70,210)}ms`;observer.observe(el)}});
document.querySelectorAll('.filters button').forEach(button=>button.addEventListener('click',()=>{document.querySelector('.filters .active').classList.remove('active');button.classList.add('active');document.querySelectorAll('.gallery-item').forEach(item=>item.classList.toggle('hidden',button.dataset.filter!=='all'&&!item.dataset.category.includes(button.dataset.filter)))}));
const lightbox=document.querySelector('.lightbox'),lightboxImage=lightbox.querySelector('img');let visibleItems=[],lightboxIndex=0;
function openImage(item){visibleItems=[...document.querySelectorAll('.gallery-item:not(.hidden)')];lightboxIndex=visibleItems.indexOf(item);lightboxImage.src=item.dataset.src;lightboxImage.alt=item.querySelector('img').alt;lightbox.showModal()}
function moveLightbox(dir){lightboxIndex=(lightboxIndex+dir+visibleItems.length)%visibleItems.length;lightboxImage.src=visibleItems[lightboxIndex].dataset.src;lightboxImage.alt=visibleItems[lightboxIndex].querySelector('img').alt}
document.querySelectorAll('.gallery-item').forEach(item=>item.addEventListener('click',()=>openImage(item)));lightbox.querySelector('.lightbox-close').addEventListener('click',()=>lightbox.close());lightbox.querySelector('.lightbox-prev').addEventListener('click',()=>moveLightbox(-1));lightbox.querySelector('.lightbox-next').addEventListener('click',()=>moveLightbox(1));lightbox.addEventListener('click',e=>{if(e.target===lightbox)lightbox.close()});addEventListener('keydown',e=>{if(!lightbox.open)return;if(e.key==='ArrowLeft')moveLightbox(-1);if(e.key==='ArrowRight')moveLightbox(1);if(e.key==='Escape')lightbox.close()});
document.querySelector('#cake-form').addEventListener('submit',e=>{e.preventDefault();const d=new FormData(e.currentTarget),message=`Hello Marbl Hearth,\n\nMy name is ${d.get('name')}.\n\nI'm enquiring about a cake for:\n${d.get('occasion')}\n\nEvent date:\n${d.get('date')}\n\nTheme:\n${d.get('theme')||'To be discussed'}\n\nApproximate size:\n${d.get('size')||'To be discussed'}\n\nMessage:\n${d.get('message')||'No additional message'}\n\nPlease let me know availability and pricing.`;window.open(`https://wa.me/263772901103?text=${encodeURIComponent(message)}`,'_blank','noopener,noreferrer')});
